### ISSUE TITLE
Error is autoinstall script

### ISSUE THREAD

**Issue by securisec** [wekan/wekan-autoinstall#10]
Have been trying to use the auto install script but i keep running into this error. Is there a fix for this?

npm WARN npm npm does not support Node.js v0.10.40
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! Object function (err) {
npm ERR!         if (err) return cb(err)
npm ERR!         fs.fsync(fd, function (err) {
npm ERR!           if (err) return cb(err)
npm ERR!           fs.close(fd, cb)
npm ERR!         })
npm ERR!       } has no method 'toLowerCase'

**Comment by anselal** [comment]
@securisec There have been some changes to wekan in the requirements that I haven't been able to fix, because of work load. You can take a look at https://github.com/wekan/wekan/wiki/Install-and-Update#install-manually-releases and figure out the requirements and adapt to script to that. I think I will be able to update the script in a month or so.

**Comment by securisec** [comment]
Thanks! I wasnt quite able to make it work, but will look forward to the new autoinstall script.
